webInterface:
  # 浏览器driver的路径
  chrome:
    path: "H:/4.GitHub/4.python_code/TaobaoProductMonitor/resource/driver/chromedriver.exe"
  edge:
    path: "H:/4.GitHub/4.python_code/TaobaoProductMonitor/resource/driver/msedgeriver.exe"
log:
  # 日志配置
  level: INFO
  filename: 'log/product_monitor.log'
  format: '%(asctime)s [%(threadName)s-%(process)d-%(thread)d] - %(filename)s - [line:%(lineno)d] - [%(levelname)s]: %(message)s'
taobao:
  # 定时任务的cron表达式，具体格式为，分钟，小时，日期，月份，周几
  cron: '* 6,20 * * 2,4'
mail:
  # 邮件配置
  host: smtp.163.com
  sender: cmrhyq@163.com
  license: SAPJXKYKNJICQDJH
database:
  # 数据库配置
  host: "localhost"
  port: 3306
  user: "root"
  pass: "Hyq0901."
  db: "store"